apiVersion: v1
data:
  mesh: |-
    configSources:
      - address: k8s://
      - address: xds://meshregistry.mesh-operator.svc:16010
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    extensionProviders:
    - envoyOtelAls:
        port: 4317
        service: opentelemetry-collector.istio-system.svc.cluster.local
      name: otel
    rootNamespace: istio-system
    trustDomain: cluster.local
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system