apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: meshregistry
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: registry.baidubce.com/csm/slime-meshregistry
    tag: fix-bug-841427a_linux_amd64-dirty_bcdc6b5
    #repository: docker.io/slimeio/slime-meshregistry
    #tag: v0.8.0
  module:
    - name: meshregistry
      kind: meshregistry
      enable: true
      general:
        LEGACY:
          NacosSource:
            Enabled: true
            RefreshPeriod: 30s
            Address:
              - "http://nacos:8848"
            Mode: polling
